### ISSUE TITLE
Terminator droids are too powerful

### ISSUE THREAD

**Issue by petergaultney** [kyranf/robotarmyfactorio#108]
One thing that makes me enjoy mid-game Robot Army a little less is that the Terminator droids are just way too strong against biters. Whereas I can unleash two squads of 50 Battle Droids and they'll barely make it through two standard-sized biter colonies, a single squad of 25 Terminators will chew through 20-30 bases before being extinguished. 

One change I've made in my own version is to turn their healing factor down to 0. It seems to me that the biters are unfairly deprived of nearly all the damage they've done, since the Terminator droids will pretty much heal all the way between battles. At least with a 0 healing factor, the biters can chip away at them over time.

In previous games, even the end game biters did nothing, really, to stop the march of my Terminators. 

One of the things I like best about the idea of Robot Army is that it provides an automated method of keeping the biters at bay, while also providing a gameplay-enhancing resource sink and logistics issue (how do I keep droids flowing to my outposts along with repair packs, etc.?). But Terminators seem to me to wipe out all of that extra complexity by the midgame. Yes, they're super expensive. But by the time I can start using them, I should have enough economy to keep producing them consistently, if not quickly.

**Comment by kyranf** [comment]
The intention of the healing factor was to represent personal shields (but weak ones) that were meant to recharge slowly between battles, and it kind of works but you are right it probably needs tuning. 

There's an issue with the way the game is scaled too - because the technology of the player is independent of the biter evolution, a player can turtle/play it safe all the way until terminators and then unleash them on very un-evolved biters, and literally wipe the map before the evolution catches up to provide large biters/spitters and of course, behemoths and massive bases of large worms are the only real threat to terminators. 

Because factorio is an unlimited resource game, at SOME point, the player will eventually get to the point where anything is 'cheap' and that they can mass produce so many terminators that they can sprinkle them like seasoning on a fine Italian pasta. So I  guess we need to find the balance for mid-game and late-game tech, and somehow relate that to evolution %.  

What some players get caught without their guard up is letting loose a whole bunch of battle droids and their evolution % cranks up significantly in response to the squads killing them, and then suddenly large biters/spitters rock up and trash the player's army instantly and then go steamroll the player's base because they were only dealing with small/mediums before they sent out the troops. 

That's an interesting aspect to using the mod, and it's really hard to balance that. If I could do automated tests I could have a 'known' biter base at various % evolution and send known squads of known unit types and various levels of upgrades and try to plot the effectiveness and do some balancing on real data.

**Comment by petergaultney** [comment]
Yeah, I 100% agree that balancing is almost impossible given the game mechanics.

Of course, one solution would be to cheat by directly reading the evolution percentage and scaling the actual effectiveness of the droids to it. Maybe not the HP, but their damage? I don't actually know that this is possible, but I assume you can modify a unit prototype in-game.

Another (possibly better) solution would be to write our own "companion mod" that instead auto-scales (perhaps with some lag) evolution to the player's droid types and counts. Only ever increasing the evolution, I would think. Again, this is a bit cheat-y, but it would at least allow for relatively balanced gameplay until the endgame. I've actually done my own dynamic (but manual) balancing in the past by scaling the speed at which the biters expand. This can be a very effective counter even to Terminators. pseudo-code: if (distance_nearest_biter_base_to_player > X): lower_max_and_min_expansion_times_by_Y()

I suggested a companion mod because I assume some users enjoy steamrolling with Terminators. On the other hand, it would probably make more sense to just make this a config option that we advertise clearly.

**Comment by kyranf** [comment]
people should be using bobs enemies and rampant AI or Misanthrope if they want a challenge hehe. Natural Evolution is also a major one, it cranks up the HP of spawners and worms and in general the biters are much harder.  against vanilla biters with no fancy AI to help them, and no special damage types (like bob's biters), the terminators definitely steamroll things. 

I don't think we can change prototypes in-game, only during the game loading during the data-updates phase. Once ingame, you can access the raw prototypes but only for reading ( IIRC )

**Comment by kyranf** [comment]
Closing pending future balancing.. noted though - perhaps need more scaling via expensive tech.
