### ISSUE TITLE
Error when removing assembler

### ISSUE THREAD

**Issue by Yousei9** [kyranf/robotarmyfactorio#115]
Removing an assembler crashes at 
/robolib/eventhandlers.lua:342: attempt to index local 'assembler'

Seems to only happen with GLOBAL_TARGETING_TYPE = 3

**Comment by kyranf** [comment]
thanks, i'll look into it. Is repeatable? Just setting global type to 3 and then removing an assembler some time during play?

**Comment by Yousei9** [comment]
For me it was very consistent with type 3 and never happened at type 1. I haven't tested type 2.

**Comment by kyranf** [comment]
yes, should be mode. blame Dauphin. Anyway it turns out I already found and fixed this bug in the Unstable branch, you could grab the files from that and just replace your current mod files and you'll also get the other fixes in there. One of the fixes makes squads move away from the spawning area better without getting dragged back by new units spawning while the squad is leaving but doesn't leave fast enough..

**Comment by kyranf** [comment]
fixed in unstable
