### ISSUE TITLE
What are all this robots doing in the middle of my base?

### ISSUE THREAD

**Issue by nelbarr** [kyranf/robotarmyfactorio#68]
http://puu.sh/rkfp8/8c11f9ec21.jpg

They are inside my base,just sitting around and no robot assembly machine anywhere close.

What I did: I builded 2 robot assembly machines at my outposts to push the biters back. The robots did this and then started to idle, I guess they do not find any biters anymore. Look at my map:
http://puu.sh/rkfH5/0385574822.png . All the dots on top and on the left are idle robots. I am fine with them staying there. But what I do not understand is why some of them (alot actually) go to the middle of my base for no reason. 

A fix I can think of are 2 new buildings:
- An IDLE meet point. All robots that are idle will go to the nearest IDLE meet point
- An assembly machine that pick up nearby robots and put them into a chest.

With this 2 buildings I could collect robots that dont do anything anymore.
Also it will help reduce lag, right now I have lags every 3 seconds. 

Any chance for a lua command to kill all robots around me?
I tried this:

```
/c for key, entity in pairs(game.player.surface.find_entities_filtered{
   area={{game.player.position.x-100, game.player.position.y-100},
    {game.player.position.x+100, game.player.position.y+100}},
    name="droid_rocket"}) do
entity.destroy()
end
```

But it didnt work

**Comment by kyranf** [comment]
the entity name is droid-rocket, with a minus sign not an underscore. try that.

The other thing you can try is the "rally beacon" - place one of these to the north of your base and your squads from around the whole world will all try to move there, and will stay there until you remove the rally beacon. The rally beacon tries to command them to move to a point just below it, every ~3 seconds. 

The squads in the middle of your base may be difficult to fix though, because even if they respond to the rally point they might not be able to move fast enough to get out of the red transport belt mess that they walked into. The droids can hardly handle yellow transport belt, and red/blue is too fast for them to move properly once they touch it. There is nothing I can do about that ;(

you could, once you have used rally beacon to bring back your squads out at the top of the map, pick all of those up and then use the following to "kill" all remaining droids (the ones stuck in your base)

/c game.player.force.kill_all_units()



Your building suggestions are not bad, but the Rally Beacon is almost the same as the idle meet point, but I agree with the idea for a building that "picks up" droids. I am thinking the rally point (which is actually just a chest with a funny sprite) could be changed to pick up the droids that it brings close to it. 


When the mod is changed so that the squad AI is based around the Droid Assembling Machine, where each machine has only 1 squad that it "controls", we could easily have the squad see that it has no targets and just return to its "home" assembler by default.

**Comment by nelbarr** [comment]
Your last part sounds very interesting. I think that would fix a lot.  

And I see the Rally Point more as a personal recall "button" I can press, as it recalls all robots (also non idle ones).

I guess I will wait with fully automation of Robots until the mod is changed :)

**Comment by kyranf** [comment]
Closing to clear up issues list. If you have any more comments, please re-open
