### ISSUE TITLE
Bots get stuck in water.

### ISSUE THREAD

**Issue by Ardagan** [kyranf/robotarmyfactorio#77]
Squad went hunting pretty far away, I decided to call it back via rally point. Whole squad got stuck at the lake. Rally point is to EEN in images.
https://postimg.org/image/povvn0809/
https://postimg.org/image/5zy9o4kxh/

**Comment by kyranf** [comment]
Hi, thanks for the report. The squads getting stuck is an ongoing problem, some of which has been fixed by Factorio developers with their pathfinder updates in late  0.13.x builds. Peter has been helping me a lot lately and we have ended up at something that works pretty well, if you want, you could try the "unstable" branch here on github (replace files in mod folder, change mod folder to 0.2.4) and see if that helps.

The unstable branch has a lot of behavioural changes so make sure you back up your save file and be aware there could be bugs or script errors we haven't caught yet.

**Comment by mikejt4** [comment]
yeh same issue, a whole squad got stuck near a lake miles from my base ... even though i went and picked them up and redeployed them, they wouldn't work correctly after that ... they'd kill nearby aliens but then just sat there doing nothing. I couldn't get them to work again in that save. Which was a shame, because before that they were absolutely amazing! A few squads of terminators cleared about 100 bases and gave me huge stacks of alien tech :-)

**Comment by kyranf** [comment]
@mikejt4   was there a rally point in the map at this point? Do you remember what version of the mod you were using?

**Comment by mikejt4** [comment]
It was the latest version of the mod at the time, when I posted... about a month ago.
There were no waypoints down - I tried adding some but it didn't help much.

**Comment by kyranf** [comment]
closing for now to clean up a bit. The logic has changed a lot since then, and they might recover from this situation naturally now anyway.
