### ISSUE TITLE
Rally point behaviour seems erratic

### ISSUE THREAD

**Issue by andreboogaards** [kyranf/robotarmyfactorio#88]
When I place a rally point, all robots on the map (just riflebots atm, if that matters) seem to freeze in place. After I remove the rally point, they suddenly seem to decide they want to be at the rally point (but shortly after they get there, they move away again).

**Comment by kyranf** [comment]
Can you estimate how far away the squads were from your rally point? Can you try again with a rally point "close by" a squad and see if you you see the same freezing? I think the freezing behaviour is caused because over long distances the pathfinder actually takes so long to find a route that the squad doesn't start moving before the rally point pulses a new "move to" command, which restarts the pathfinder and therefore the squads never actually get a path and start moving because just before they get a path, the path request is re-sent. 

If you can confirm this by doing the test I asked, then I think a reasonable work-around is just a much longer time between the rally point pulsing a move-command to squads

**Comment by andreboogaards** [comment]
Yeah, squads were quite a distance from the rally point and placing it closer by does make a big difference, so your pathfinding theory sounds plausible. 

If you want to play around with my setup, the save and full modset are here: https://www.dropbox.com/sh/fzjkyhnvrevzely/AADfGYgmymnNg033E1v2ESc8a?dl=0
Player's standing next to the only rally point, there's a few squads scattered across the map, mostly north and northwest.

**Comment by kyranf** [comment]
I removed the rally points for now. To handle your army, use the map zoom view and the selection/pickup tools.
